# Generated by Django 3.1.6 on 2021-02-07 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dotsandboxesai', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='potez',
            name='id',
        ),
        migrations.AlterField(
            model_name='potez',
            name='id_partije',
            field=models.UUIDField(primary_key=True, serialize=False, unique=True),
        ),
    ]
